"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans, Raleway } from "next/font/google";

const openSans = Open_Sans({ subsets: ["latin"] });
const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <style jsx global>
        {`
          .raleway {
            font-family: ${raleway.style.fontFamily};
          }
        `}
      </style>
      <body className={openSans.className}>{children}</body>
    </html>
  );
}
